name: Run Gradle on PRs
on: [pull_request, push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run Format Check (If this step fails run ./gradlew spotlessJavaApply in your powershell/terminal/console etc)
      run: ./gradlew spotlessJavaCheck

    - name: Execute Gradle build
      run: ./gradlew build